### ISSUE TITLE
[Feature] Primal dual active set method

### ISSUE THREAD

**Issue by Mamba413** [abess-team/skscope#18]
It seems that the primal-dual active set (PDAS) algorithm is also a (potentially) powerful algorithm for sparsity optimization. It would helpfully enrich our support solvers if it is implemented. 

Reference:

- Wen, C., Zhang, A., Quan, S., & Wang, X. (2020). BeSS: An R Package for Best Subset Selection in Linear, Logistic and Cox Proportional Hazards Models. Journal of Statistical Software, 94(4), 1–24. https://doi.org/10.18637/jss.v094.i04

**Comment by star-dust-ctrl** [comment]
I implemented the algorithm in `solver.py` by inheriting `BaseSolver`. The tests in `pytest` and necessary descriptions in documentation are implemented as well.
