### ISSUE TITLE
[Testing] improve test coverage

### ISSUE THREAD

**Issue by Mamba413** [abess-team/skscope#72]
@chenpnn I find that the file `[utilities.py](https://app.codecov.io/gh/abess-team/skscope/commit/e7031f68f26eed1fd5301b2c511ca1936dbda380/blob/skscope/utilities.py)` is not well covered by python testing. 
@bbayukari Shall we our test also cover this utility file?

**Comment by bbayukari** [comment]
I have added a test in #[9ad8d30](https://github.com/abess-team/skscope/commit/9ad8d3020761d6d629aef6d5ebcce4293f61a9aa).
Hope this will be helpful.
