### ISSUE TITLE
[Feature] Support for sparse matrix and more optimizers

### ISSUE THREAD

**Issue by chenpnn** [abess-team/skscope#79]
I have two suggestions for possible improvements as follows:
1. **Sparse matrix:** In some practical problems (e.g.,  document classification) where the covariate matrix is extremely sparse, can ``skscope`` utilize the characteristic of  _sparse matrix_ to imporve the efficiency of storage and computation? Some reference may be helpful such as [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html) or its JAX version [jax.scipy.sparse](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.sparse.linalg.cg.html#jax.scipy.sparse.linalg.cg).
2. **Optimizers:** I find that the base numeric solver for ``skscope`` is mainly based on ``nlopt`` now, and I wonder whether it is possible to support more optimizers. For example, the differentiable optimizer [JAXopt](https://jaxopt.github.io/stable/) may be more suitable for general (unconstrained, constrained and composite) optimization problems .

Thanks!

**Comment by Mamba413** [comment]
The requested feature also covers this one: https://github.com/abess-team/skscope/issues/58

**Comment by Mamba413** [comment]
Hi @chenpnn ! Thank you for your comment. Sparse matrix is now supported by `skscope`. Please see this example document for its common usage: https://skscope.readthedocs.io/en/latest/feature/ComputationalTips.html.
